Add lint checking to CI.
tokio-rs/prost pull request #1008
Opened 2024-03-17 18:23 UTC by gibbz00

Depends on #1007.

2024-04-02 12:33 UTC, caspermeijn commented on prost-types/src/any.rs
> +        if let (Some(expected), Some(actual)) = (
Could this be further simplified?
```suggestion
        if TypeUrl::new(&expected_type_url) == TypeUrl::new(&self.type_url) {
```

2024-04-02 12:33 UTC, caspermeijn commented on src/encoding.rs
> +        decode_varint_slow(&mut u64_max_plus_one)
These `clone()` are on purpose. See https://github.com/tokio-rs/prost/pull/977

2024-04-02 12:33 UTC, caspermeijn commented on src/encoding.rs
> +            let roundtrip_value = decode_varint_slow(&mut &*encoded).expect("slow decoding failed");
The re-borrow was replaced removed. See #977

2024-04-05 08:04 UTC, caspermeijn requested changes
I am sorry to say this, but this too many different types of changes to the code base for me to properly grasp. I find it difficult to review this PR.

Please split the changes into parts for each type of change. That could be separated commits or separated PR.

For example split all `#[cfg(not(feature = "std"))]` changes into one commit and all the `&(ref x)` changed into another commit.

2024-04-05 09:42 UTC, gibbz00 commented
> I am sorry to say this, but this too many different types of changes to the code base for me to properly grasp. I find it difficult to review this PR.

It's okay. `git add --patch` is our friend for this :) Fixed.

2024-04-05 10:00 UTC, caspermeijn approved these changes
Thank you for splitting the commits.

I changed the PR title to better represent the work you did.

2024-04-05 11:51 UTC, gibbz00 commented on src/encoding.rs
> +    fn variant_slow_overflow() {
Thanks! Helps with debugability if one of them fails too ;)

2024-04-09 15:05 UTC, caspermeijn approved these changes

2024-04-09 15:12 UTC, merged