Change generated functions signatures to remove type parameters
tokio-rs/prost pull request #1045
Opened 2024-04-26 12:52 UTC by shizzard

Fixes #1042

2024-04-26 13:32 UTC, caspermeijn requested changes
The changes look good. Just a one comment: You should add a test to confirm your example works.

2024-04-26 14:06 UTC, shizzard commented
> You should add a test to confirm your example works.
@caspermeijn I thought about it, that seem to be a good practice, but this test will only fail if somebody will add the generic type parameter with the same name (e.g. `pub fn encode<T>...` will still pass). It seems impossible to create a useful test that will ensure no shadowing will occur in the future. Are you sure this test is a good addition?

2024-04-26 14:53 UTC, shizzard commented
@caspermeijn Alright, what is the best place to put this test? I'm not really familiar with the prost project structure, can you help me with that?

2024-04-26 14:56 UTC, caspermeijn commented
> @caspermeijn Alright, what is the best place to put this test? I'm not really familiar with the prost project structure, can you help me with that?

You could do something similar to this: https://github.com/tokio-rs/prost/blob/master/tests/src/no_unused_results.proto

If you search for `no_unused_results`, you can find all the places where you need to add something.

2024-04-26 15:58 UTC, shizzard commented
The test is `no_shadowed_types`, I checked it was successfully executed:
```
...
test no_shadowed_types::dummy ... ok
...
```

2024-04-29 17:34 UTC, caspermeijn approved these changes
Looks good to me. This is a breaking change, so it has to wait for the next major release. Thank you for your contribution.

2024-05-03 07:18 UTC, caspermeijn commented
> @caspermeijn latest commit changes the rest of `::prost::Message` trait as you noted in discord.

Thank you. I am sorry to keep finding more stuff to do: In `prost/src/encoding.rs` and in `prost/src/lib.rs` are some more easy to replace `where B: Buf` statements. Could you also replace those?

I think when doing this breaking change, we should do all of them at once.

2024-05-03 16:00 UTC, shizzard commented
> I think when doing this breaking change, we should do all of them at once.

I did try to make these changes within `encoding.rs`, but there are several cases where it is not possible:
- `FnMut` type does not allow dynamic dispatch
- closures does not allow dynamic dispatch

Also, these functions are doing tight-loop decoding and may gain some performance benefits from static dispatch. There are also no way these functions type parameters may shadow user-defined types.

You still think to make these changes where it is possible?

2024-05-05 19:27 UTC, caspermeijn commented
> Also, these functions are doing tight-loop decoding and may gain some performance benefits from static dispatch. There are also no way these functions type parameters may shadow user-defined types.

`impl Buf` will not do a dynamic dispatch, maybe you are thinking of the `dyn` keyword. As I understand, the behavior is the same as the `where B: Buf` statement, but it doesn't have the explicit generic type. So I think it will be fine.

> You still think to make these changes where it is possible?

I agree those two complex `where` case should stay the same. I would like to see the simple cases changes and the more complicated cases can stay as is.

2024-05-06 12:14 UTC, shizzard commented
> `impl Buf` will not do a dynamic dispatch, maybe you are thinking of the `dyn` keyword.

Yes, you're right, for some reason I thought that this will do a dynamic dispatch.

I did the changes you wanted; there are 6 more places where the buffer is type parametrized (search for `"B: Buf"` in `encoding.rs` file).
I tried to do the same for `M: Message`, but it broke one test on compile time (with cryptic error message that I don't fully understand actually), so I reverted the `M: Message` type changes.

2024-05-08 07:07 UTC, caspermeijn commented
> I did the changes you wanted; there are 6 more places where the buffer is type parametrized (search for `"B: Buf"` in `encoding.rs` file). I tried to do the same for `M: Message`, but it broke one test on compile time (with cryptic error message that I don't fully understand actually), so I reverted the `M: Message` type changes.

That looks good. Thank you for this cleanup. We could always do the `impl Message` at another time.

2024-05-08 07:07 UTC, caspermeijn approved these changes

2024-05-20 16:42 UTC, merged