fix(prost-build): Remove `derived(Copy)` on boxed fields
tokio-rs/prost pull request #1157
Opened 2024-09-13 21:40 UTC by ldm0

Fix one of the problems I found while rebasing #705: boxed fields are not `Copy`

2024-09-16 07:02 UTC, caspermeijn requested changes
So, basically `Config::boxed()` is broken in the latest released version because in many circumstances it will derive copy on the manually marked boxed field.

I would like to see a new test that prevents this in the future.

2024-09-17 01:05 UTC, ldm0 commented on prost-build/src/message_graph.rs
> -    pub fn can_message_derive_copy(&self, fq_message_name: &str) -> bool {
> Currently, if two messages include each other, the automatic boxing happens at both sides of the recursive include. If one side is already manually boxed, then it doesn't have to be at the other side.

That's interesting. I created another feature PR to address this: https://github.com/tokio-rs/prost/pull/1160

2024-09-17 01:06 UTC, ldm0 commented
> I would like to see a new test that prevents this in the future.

Test added.

2024-09-20 06:09 UTC, caspermeijn approved these changes
Thank you for your contribution

2024-09-20 06:18 UTC, merged