Correct codeblocks to not break `cargo test --doc`
tokio-rs/prost pull request #633
Opened 2022-04-23 11:40 UTC by kinnison

I have been working with protocol buffers whose documentation includes code blocks, often things like example service descriptions and the like (consider https://github.com/googleapis/googleapis/blob/master/google/api/http.proto#L67-L81 )

As such, it's important that by the time prost-build has run, the code blocks in those comments have been transformed into something safe from `rustdoc`'s test extractor.

This PR is split into three commits.  The first adds the code-block processing support.  The second fixes up ensuring there's leading spaces in the comments to retain the pleasant-ish human look, and the third updates the generated code files for `prost-types` so that things are consistent.

2022-04-23 12:12 UTC, kinnison commented
I can see that this is failing with the MSRV of 1.51. I'll look into that.

2022-04-23 12:25 UTC, kinnison commented
Based on the rule mentioned in <https://github.com/tokio-rs/prost/pull/552> I *think* it's OK for me to bump MSRV to 1.53.0.

2022-05-20 09:38 UTC, kinnison commented
@LucioFranco We spoke about this back when I first wrote the patch - is there any chance it can be considered soon?  If it needs big changes then I'm now back from my travels and able to spend time on it again.  In the meantime I've rebased onto current mainline.

2022-05-23 18:45 UTC, LucioFranco commented
Hey! Sorry, I must have closed my tab when looking at this. So I am not convinced I want to add pulldown_cmark as a dependency (knowing people will complain). I wonder if we can either 1) vendor the code required to do this parsing or 2) implement a custom way to just swap out the way it generates the markdown. What are your thoughts?

(btw thanks for the ping, I sometimes lose track of things gh isn't always the best at keeping track)

2022-05-23 19:28 UTC, kinnison commented
Regarding not wanting pulldown-cmark, I can understand that, and I tried to write something which would avoid it, but ultimately there's no *standard* for the comments in protobuf files; and rustdoc *does* use pulldown-cmark which basically led me to "this is ultimately the best bet" - I'd be happy to add a feature flag for it though.

2022-05-23 21:35 UTC, LucioFranco commented
@kinnison That is fair, I think actually an opt-in feature flag is worth it so people can disable it. I'd be happy to merge that.

2022-05-23 22:20 UTC, kinnison commented
I'll get on that tomorrow then. Also I'll see if I can minimise features on the new deps too

2022-05-24 09:33 UTC, kinnison commented
I've taken your comment to mean that you want an off-by-default feature flag, so I've put that together.  For ease of having the bootstrapped files still nice for `cargo test --doc` I made the tests crate turn the flag on.  Assuming this makes it through CI, I think that'll be what we need.

It's worth noting though that the extra deps are pretty small; however I accept that not everyone will want their doc strings being modified like this, so I'm happy with it being optional-off-by-default.

2022-05-24 10:14 UTC, kinnison commented
I apologise for the noise on this PR, the minversions check threw me for a loop.

2022-05-24 19:38 UTC, LucioFranco requested changes
Looks good overall, just would like to see some more tests, then we can merge.

2022-05-24 21:58 UTC, kinnison commented on prost-build/src/ast.rs
> +        fn get_lines<S>(comments: S) -> Vec<String>
So the `bootstrap` test essentially covers this, but I'd be happy to add some unit tests or similar to cover both sides of the binary option.  Thanks for the review, I'll try and do that tomorrow.

2022-05-24 22:01 UTC, LucioFranco commented on prost-build/src/ast.rs
> +        fn get_lines<S>(comments: S) -> Vec<String>
No problem, I appreciate you pushing through on this!

2022-05-25 19:51 UTC, kinnison commented on prost-build/src/ast.rs
> +        fn get_lines<S>(comments: S) -> Vec<String>
I've cleaned things up a bit; added a test which has all the relevant cases for the codeblocks, and also checks that in non-cleanup mode that the text is passed through unchanged.

Also rebased again.

2022-05-25 19:59 UTC, kinnison commented
Yep, I'll add the docs. (and fix the minversions thing which bit again)

2022-05-25 20:06 UTC, kinnison commented
Hopefully that'll do the trick.  If that isn't good enough documentation then please let me know what else you would like to see - I'm awful at writing these things :D

2022-05-25 20:13 UTC, LucioFranco approved these changes
🔥 🚀  Thanks!

2022-05-25 20:32 UTC, kinnison commented
We have a green CI run 🎉

2022-05-25 20:39 UTC, merged