feat: add derive feature
tokio-rs/prost pull request #992
Opened 2024-03-01 12:07 UTC by tottoto

Related to #991.

2024-03-08 09:04 UTC, caspermeijn reviewed
It would be good to document the features we publicly expose. I don't think `rustdoc` will do that for you. 

Are you willing to document the features in the README of each public crate?

2024-03-08 11:54 UTC, tottoto commented
> It would be good to document the features we publicly expose.

I think so too. However I think that it is out of scope from this pull request as there is not a document about `features` in the README (there is about no_std crates, but it is not a comprehensive document about features). I think it should be a separated concern. I think the diff scope should be minimum as possible.

2024-03-08 11:55 UTC, tottoto commented
> It would be good to document the features we publicly expose.

I think so too. However I think that it is out of scope from this pull request as there is not a document about `features` in the README (there is about no_std crates, but it is not a comprehensive document about features). I think it should be a separated concern. I think the scope should be minimum as possible.

2024-03-15 12:36 UTC, caspermeijn commented
> > It would be good to document the features we publicly expose.
> 
> I think so too. However I think that it is out of scope from this pull request as there is not a document about `features` in the README (there is about no_std crates, but it is not a comprehensive document about features). I think it should be a separated concern. I think the scope should be minimum as possible.

I understand

2024-03-15 12:43 UTC, caspermeijn requested changes
- `prost-types` uses the old derive feature. I suggest replacing it: https://github.com/tokio-rs/prost/blob/e3d708c0e031d71b87bb5ba5c0c3aad3393275fd/prost-types/Cargo.toml#L25
- `test-no-std` uses the old derive feature. I suggest replacing it: https://github.com/tokio-rs/prost/blob/e3d708c0e031d71b87bb5ba5c0c3aad3393275fd/tests-no-std/Cargo.toml#L27
- CI used the old derive feature, but I think this is a good one, as it confirms this is a non-breaking change: https://github.com/tokio-rs/prost/blob/e3d708c0e031d71b87bb5ba5c0c3aad3393275fd/.github/workflows/ci.yml#L61

2024-03-15 13:29 UTC, tottoto commented
> - prost-types uses the old derive feature. I suggest replacing it: 

Since it will be a breaking change, it is not recommended.

> - test-no-std uses the old derive feature. I suggest replacing it: 

Updated.

2024-03-15 14:53 UTC, caspermeijn approved these changes
LGTM

2024-03-15 14:53 UTC, caspermeijn commented
Thank you for your contribution

2024-03-15 14:59 UTC, merged